### PR TITLE
Eliminate use of {{STATIC_URL}} in templates: #469

### LINKED ISSUE #469: Reorganize static files and their usage
- Move astrobin's static files to `/astrobin/static/astrobin`
- Use the {% static %} tag thoroughly

### PR DESCRIPTION
**Pull request by skaven81**
Closes #469

### CODE REVIEW

**Comment by skaven81** [comment]
Note you will want to merge #598 before you merge this one.

**Comment by skaven81** [comment]
Getting a test failure on image upload:
```
FAIL: test_image_promote_view (astrobin.tests.test_image.ImageTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/astrobin/tests/test_image.py", line 1610, in test_image_promote_view
    self.assertTrue((published - image.uploaded).total_seconds() < 1)
AssertionError: False is not true
```

I've run out of time to poke at this today.  @siovene if this looks like a quick fix, feel free to jump in, otherwise I'll see if I can get to it tomorrow.

**Comment by skaven81** [comment]
Also, there are a few places (notably, where localization is involved) where `{% static %}` is a bit awkward to use, due to the need to interpolate the locale into the URL.  There are a couple approaches to this. The one I took is to use `{% static 'baseurl/' %}{{insert locale here}}.js`.  But the other way would be to create a variable on the fly using `with`:

```
{% with 'astrobin/js/somelocalized-'|add:request.LANGUAGE_CODE|add:'.js' as js_path %}
  {% static js_path %}
{% endwith %}
```

Not sure if you'd prefer this solution over what I've implemented.

**Comment by skaven81** [comment]
Found the bug, fixed it. I think this is ready to go.

**Comment by siovene** [comment]
There are still some references to `STATIC_URL`:

- `astrobin/settings/components/pagination.py`
- `astrobin/views/__init__.py`

Can they be eliminated?

> Note you will want to merge #598 before you merge this one.

Sure but that wasn't really required, was it? You accidentally created your branch on top of that one instead of `master`. You can still rebase and force push.

> Getting a test failure on image upload

See #557. I believe that something is broken in the way the `published` field is handled. Either the code is wrong, or the test is wrong. It works by a lucky accident on Travis but it often fails for me locally. Anyway, unrelated to this issue.

> Found the bug, fixed it. I think this is ready to go.

Which bug?

**Comment by siovene** [comment]
> Not sure if you'd prefer this solution over what I've implemented.

I'll have to check if it works with cache-busting in production.

**Comment by skaven81** [comment]
> Can they be eliminated?

Most likely, I'll take a look.

> Which bug?

There was a missing quote in one of the `{% static %}` tags in a template that was causing a test failure (syntax error).  This was (apparently) in addition to #557

**Comment by siovene** [comment]
Ok this PR is fine now but it's dependent on #557

**Pull request merged**
