### PR TITLE
(equipment) Add camera list to sensor serializer

### PR DESCRIPTION
**Pull request by sastels**
re https://www.notion.so/astrobindotcom/3a1dc9974a89400686247f2bce3108b8?v=5ca6bcdff83a49f6b927b9c235bb61df&p=fe21b06abbec4e57963dc3e49d3ba54a&pm=s

Add the list of cameras using a given sensor to the sensor serializer.

Will be used by
https://github.com/astrobin/astrobin-ng/pull/1472

Verified that this PR works with current astrobin-ng (June 2, 4a57179d56fb5e6c7b1b5546aa21b9ec5a98c026)

### CODE REVIEW

**Comment by sastels** [comment]
Should this have added testing?

**Comment by siovene** [comment]
> Should this have added testing?

@sastels tests wouldn't hurt 😀 I rely on tests a lot to avoid regressions. This one would go here:

`astrobin_apps_equipment/tests/test_api_sensor_view_set.py`

**Comment by siovene** [comment]
@sastels would you mind changing this so that the cameras are sorted by popularity? I think it would make sense for the frontend to show them that way. You can simply add `.order_by('-user_count')` to the queryset.

If you're testing this, please note that user_count is updated when the search index is updated, so you'll need to run `./manage.py update_index`.

Thanks!

**Comment by sastels** [comment]
Changed to
```
        return Camera.objects.filter(sensor=item.id).values_list('pk', flat=True).order_by('-user_count')
```

Having problems saving an image locally :/ looks like it's trying to use boto to upload to s3 and erroring out because there's no credentials. Any way to emulate this locally? Or configure to point to S3 in my own account 🤔

**Comment by siovene** [comment]
Hi @sastels,

the default settings should use local storage, not S3, in theory. Tho I admit that that part could be broken because personally I use a dev bucket for local development.

Are you overriding anything in `/docker/astrobin.env`?

The storage is governed by `storage.py` and `s3utils.py`. In the latter file, you see that unless `AWS_S3_ENABLED` is `True`, AstroBin uses  `OverwritingFileSystemStorage`.

**Comment by sastels** [comment]
I haven't touched `astrobin.env`, **however** yesterday when I tried to do the final save of an image I got a stack trace and a popup in the corner saying the staff had been notified of the problem. today it just works... 

So I have some local images! Running the `update_index` (on the astrobin docker container?) doesn't seem to have worked... I get a "update is not implemented" error:
```
# ./manage.py update_index
System check identified some issues:

WARNINGS:
?: (urls.W003) Your URL pattern '^account/login/$' [name='two_factor:login'] has a name including a ':'. Remove the colon, to avoid ambiguous namespace references.
astrobin.GearRenameRecord.gear: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
Indexing 0 nested comments
Indexing 3 equipment brands
/usr/local/lib/python3.8/dist-packages/haystack/backends/simple_backend.py:24: UserWarning: update is not implemented in this backend
  warn("update is not implemented in this backend")
Indexing 0 equipment brand listings
Indexing 2 sensors
Indexing 7 cameras
Indexing 1 telescopes
Indexing 0 mounts
Indexing 0 filters
Indexing 0 accessorys
Indexing 0 softwares
Indexing 3 users
Indexing 0 Topics
Indexing 0 Posts
Indexing 2 images
```
and the numbers haven't changed in the app
image

(Note: I uploaded a pic and set the telescope to the evo 8)

This is really another issue not related to getting the gamera list in the sensor serializer, mind you - we can talk about it somewhere else if you'd like.

**Comment by siovene** [comment]
Hi @sastels,

sorry, my bad. I forgot that the default development configuration uses a dummy search backend.

You can see this in `haystack.py` because `os.environ.get('ELASTICSEARCH_URL')` is not defined.

Locally I just use a dev AWS elasticsearch instance. I can't recall if I had some trouble running `elasticsearch` locally in a docker container, or if I was in a hurry when I did that (it was many years ago).

If you plan to continue helping, it makes sense in either attempt to add `elasticsearch` to the `docker-compose` configuration, or setup an account with a free option (AWS should be free for development purpose, because you won't be likely to get out of the free tier in terms of number of API calls just by yourself).

For the purpose of testing this patch, you can simply set `image_count` and `user_count` to a made up number using `./manage.py shell` inside the `docker` instance.

Just to be verbose:

```
# Connect to the container
docker exec ${CONTAINER_ID} -it ./manage.py shell
>>> from astrobin_apps_equipment.models import Sensor
>>> x = Sensor.objects.get(id=12345)
>>> x.image_count = 20
>>> x.save()
```

BTW you can contact me on Telegram @siovene :)

**Comment by sastels** [comment]
sweeet, manually set the user count for what used to be the second camera in the list to 1 and now it's the first camera in the list 🎉 

Can probably set the user count in the unit test, then could unit test the order too. Let me look into that...
(sorry, we really have a "test everything" culture at my work 😬 )

**Comment by siovene** [comment]
@sastels that's awesome, thanks! I also try to test as much as reasonable. It's saved my ass way more times than I care to admit :)

**Pull request merged**
